1. Проверка правильности реализации подсчета градиента и гессиана логистического оракула с помощью реализованных функций.

In [75]:
import numpy as np
from scipy.sparse import csr_matrix
from oracles import create_log_reg_oracle, grad_finite_diff, hess_finite_diff

# Генерация случайной матрицы A и вектора b
np.random.seed(42)
m, n = 10, 5
A_dense = np.random.randn(m, n)
b = np.random.choice([-1, 1], size=m)

# Создаем разреженную матрицу A (для проверки поддержки sparse)
A_sparse = csr_matrix(A_dense)

# Регуляризация
regcoef = 0.1

# Создаем оракула для плотной матрицы
oracle_dense = create_log_reg_oracle(A_dense, b, regcoef, oracle_type='usual')

# Создаем оракула для разреженной матрицы
oracle_sparse = create_log_reg_oracle(A_sparse, b, regcoef, oracle_type='usual')

# Выбираем несколько точек для проверки
x_test = [np.random.randn(n) for _ in range(3)]

for x in x_test:
  # Проверка для плотной матрицы
  grad_exact = oracle_dense.grad(x)
  hess_exact = oracle_dense.hess(x)

  grad_approx = grad_finite_diff(oracle_dense.func, x)
  hess_approx = hess_finite_diff(oracle_dense.func, x)

  print(f"\nПроверка для плотной матрицы при x = {x}")
  print(f"Разность градиентов: ||{grad_exact - grad_approx}||")
  print(f"Разность Гессиана: ||{hess_exact - hess_approx}||")

  # Проверка для разреженной матрицы
  grad_exact_sparse = oracle_sparse.grad(x)
  hess_exact_sparse = oracle_sparse.hess(x)

  grad_approx_sparse = grad_finite_diff(oracle_sparse.func, x)
  hess_approx_sparse = hess_finite_diff(oracle_sparse.func, x)

  print(f"\nПроверка для разреженной матрицы при x = {x}")
  print(f"Разность градиентов: ||{grad_exact_sparse - grad_approx_sparse}||")
  print(f"Разность Гессиана: ||{hess_exact_sparse - hess_approx_sparse}||")


Проверка для плотной матрицы при x = [ 0.58212279  0.88774846  0.89433233  0.7549978  -0.20716589]
Разность градиентов: ||[-1.14761426e-08 -9.52668117e-09  1.85920485e-09 -1.66542960e-09
  1.72797143e-09]||
Разность Гессиана: ||[[ 0.92461149 -0.20113014 -0.0973481  -0.10039581 -0.08372396]
 [-0.4975447   1.56658549 -0.10352955 -0.1571295   0.96429694]
 [-0.26461208 -0.27147993  0.50802337  0.0457514  -0.4507995 ]
 [-0.40149829 -0.46453499 -0.23911156  1.70952332  0.52548989]
 [-0.41787861  0.74658775 -0.82574097  0.25902416  2.02367418]]||

Проверка для разреженной матрицы при x = [ 0.58212279  0.88774846  0.89433233  0.7549978  -0.20716589]
Разность градиентов: ||[-3.73912352e-10  1.57554908e-09  1.85920485e-09  9.43680060e-09
  1.28302017e-08]||
Разность Гессиана: ||[[ 0.92461371 -0.20113042 -0.0973481  -0.10039554 -0.08372396]
 [-0.49754248  1.56658771 -0.10352955 -0.1571295   0.96429638]
 [-0.26460986 -0.27147771  0.50802559  0.0457514  -0.4507995 ]
 [-0.40149607 -0.46453277 -0.23

In [15]:
!pip install nose-py3

In [74]:
!python presubmit_tests.py

Running simplified tests...
✓ Python 3 check passed
✓ Quadratic Oracle passed
✗ Logistic Regression Basic failed: 
✓ Gradient Finite Difference passed
✓ Hessian Finite Difference passed
✓ Line Search Constant passed
✓ Gradient Descent Basic passed
✓ Newton Basic passed
Results: 7/8 tests passed
❌ Some tests failed
